name = "Beep"
uuid = "97dd0070-d6c0-43ac-b134-ca84cdbd343e"
authors = ["Chris Jungerius <cjungerius@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
